### ISSUE TITLE
using zram with Heira

### ISSUE THREAD

**Issue by rbos** [voxpupuli/puppet-zram_generator#18]
More a question than an issue, I'm probably the problem. I'm trying to configure zram using Heira. The module is loading, but it doesn't seem to be using the Heira class. Why wouldn't the following work?

```
classes:
  - zram_generator

zram_generator::zram:
  zram0:
    zram_size: 'ram/2'
```
